### PR TITLE
added swedish information to addon.xml

### PR DESCRIPTION
**Pull request by nonew-star**

### CODE REVIEW

**Comment by elgatito** [comment]
@nonew-star Is this finished?

**Comment by antonsoroko** [comment]
@nonew-star 
btw, you might want to do new translation updates for Swedish
https://github.com/elgatito/plugin.video.elementum/pull/744/files#diff-a0be38239d01db736df00c3d7121b484c7a3de979d6aadda53c6a123f5fc7665

**Comment by antonsoroko** [comment]
@nonew-star 
btw, you might want to do new translation updates for Swedish
1. https://github.com/elgatito/plugin.video.elementum/pull/744/files#diff-a0be38239d01db736df00c3d7121b484c7a3de979d6aadda53c6a123f5fc7665
2. https://github.com/elgatito/plugin.video.elementum/pull/760/files#diff-a0be38239d01db736df00c3d7121b484c7a3de979d6aadda53c6a123f5fc7665

**Comment by nonew-star** [comment]
@elgatito yes

@antonsoroko thanks

**Pull request merged**
