### PR TITLE
Update Kickass url

### PR DESCRIPTION
**Pull request by burekas7**
Update Kickass url

Old base url was: https://katcr.to
New base url is: https://kickasstorrents.to

### CODE REVIEW

**Comment by antonsoroko** [comment]
both urls works for me. do you know what is the difference?

**Comment by burekas7** [comment]
@antonsoroko 
For me the first one gives: 403 Forbidden (Either in browser or Elementum)
The second one works on both.

**Comment by ShlomiD83** [comment]
@burekas7 both work for me.
which DNS addresses do yo use?

**Comment by burekas7** [comment]
> @burekas7 both work for me. which DNS addresses do yo use?

It doesn't matter which dns, if the new one is working for everyone why the first one not, so update to the new one is better.

**Comment by ShlomiD83** [comment]
> > @burekas7 both work for me. which DNS addresses do yo use?
> 
> It doesn't matter which dns, if the new one is working for everyone while the first one is not, so updating to the new one is better.

It's not working just for you it appears.
change it in the settings and your good.

**Pull request merged**
