### PR TITLE
Correcting filter_ts to filter_telesync

### PR DESCRIPTION
**Pull request by mancuniancol**
The settings has the wrong name for the filter telesync. Line 69 of burst.py

### CODE REVIEW

**Comment by mancuniancol** [comment]
I think I did it again LOL.  Sorry.  I've done the requests but it seems that the next two commits were included.  I will wait and I will study well git, it doesn't work as SVN :)  any ways.

At the end, I've decided starts from zero from you code.   To be clearer in the changes.

The idea about  the normalization is to make sure that all the string are unicode.  My next commit will be the TNTvillage provider which needs that normalization otherwise it will make filtering.py crashes.

**Comment by mancuniancol** [comment]
@elgatito, I didn't get any feedback. Hope everything is ok.

**Comment by elgatito** [comment]
@mancuniancol  do you have possibility and a will to join our gitter channel? I'm planning to finish Burst merges and changes, so will be easier if you could help understanding your changes.

**Comment by mancuniancol** [comment]
@elgatito yes, but do you mean elementum? or there is a channel just for burst?

**Comment by elgatito** [comment]
@mancuniancol yes, it's ElementumApp channel, one for everything :+1:

**Comment by mancuniancol** [comment]
Good.  I've joined.  Busy today, but I will read it tonight.

**Pull request merged**
