### PR TITLE
Reverting name to List_ and updating Nyaa provider

### PR DESCRIPTION
**Pull request by mancuniancol**
Sorry, to ask for two different things in the same request.  I don't know how to ask separately.
I didn't change the version in the addons.xml, though.

### CODE REVIEW

**Comment by hoshsadiq** [comment]
Why are you changing the name of `list` to `list_`?

**Comment by hoshsadiq** [comment]
What do the changes for nyaa achieve?

**Comment by mancuniancol** [comment]
@hoshsadiq answering your first question, the function as named list_ to avoid shadow to the native function list.  However, in my previous contribution, updating the ehp.py, I've changed to list.  The change is more cosmetic and to continue the naming.

About the second question.  I'm addressing this issue:  https://github.com/elgatito/script.elementum.burst/issues/42

**Comment by hoshsadiq** [comment]
Cool, in the future make sure you mention these things so people understand why a PR is raised :)

**Comment by mancuniancol** [comment]
Ok, but I was following the conversation with elgatito

#40

I didn't know that it was more people involved

**Comment by hoshsadiq** [comment]
Sorry, I'm not a core dev, I was simply curious as I do use nyaa as well :)

**Pull request closed without merging**
