### PR TITLE
Update TorrentGalaxy Color

### PR DESCRIPTION
**Pull request by ShlomiD83**

### CODE REVIEW

**Comment by elgatito** [comment]
Can't accept this as it will break providers sorting. There is a separate field for provider color in general.

**Comment by ShlomiD83** [comment]
what do you mean "break providers sorting"? I don't have issues with this configuration.
I tried using the "Color" setting but couldn't get the two colors to show up properly.

**Comment by elgatito** [comment]
@ShlomiD83 There are scripts that do generation of settings.xml depending on providers.json content.

**Comment by ShlomiD83** [comment]
If you say so, I didn't run into any problems.
I guess I'll add the color manually after each update just on my side :)

**Pull request closed without merging**
