### PR TITLE
Disable dead trackers as of 25.06.2023

### PR DESCRIPTION
**Pull request by antonsoroko**
Disable dead trackers as of 25.06.2023:
* ettv
* ilcorsarored
* torrentz
* torrentz2k
* zooqle
* skytorrents
* filebase
* worldwidetorrents
* torrent3d
* tfile
* serialz
* myxz
* nitro
* filetracker
* 3d-tracker

### CODE REVIEW

**Comment by SubEdict** [comment]
Also, no idea what's up with: skytorrents.lol

**Comment by antonsoroko** [comment]
i manually checked all URLs, some are dead, some redirect to something else. disabled all dead.

used this to get URLs list `jq '.[] | if (.enabled == true) then .base_url else empty end' providers.json`

**Comment by antonsoroko** [comment]
@elgatito Hi. Could you please take a look at my PRs in this repo please? (when you have time, of course)

**Comment by elgatito** [comment]
@antonsoroko Don't forget to run `generate_settings.py`  when you enable/disable provider, or change it's name, as it is used for addon settings.

Thanks for PRs, will check them.

**Pull request merged**
