### PR TITLE
Fix RARBG provider movie_extra_fallback2 query

### PR DESCRIPTION
**Pull request by burekas7**
Fix for RARBG provider:
tmdb mobie_extra_fallback2 query

Regarding the key: "movie_extra_fallback2"
Value was: "search_themoviedb"
Value is updated to: "search_tmdb"

### CODE REVIEW

**Comment by antonsoroko** [comment]
Have you tested it?

where you found this `search_tmdb`?

see my PR https://github.com/elgatito/script.elementum.burst/pull/276

in doc
https://webcache.googleusercontent.com/search?q=cache:gCY5Kdzz6PIJ:https://torrentapi.org/apidocs_v2.txt
```
Searching by themoviedb :
mode=search&search_themoviedb=123456&token=xxxx
```

so it should be `search_themoviedb` unless they changed it but forgot to change doc.

**Comment by burekas7** [comment]
@antonsoroko 
Yes I tested it.

For example:

Works:
`https://torrentapi.org/pubapi_v2.php?mode=search&**search_tmdb=577922**&category=14;48;17;44;45;47;50;51;52;42;46;54&format=json_extended&app_id=script.elementum.burst&token=xc1g5priz7`
It returns:
`{"torrent_results":[ .........`

Doesn't work:
`https://torrentapi.org/pubapi_v2.php?mode=search&**search_themoviedb=577922**&category=14;48;17;44;45;47;50;51;52;42;46;54&format=json_extended&app_id=script.elementum.burst&token=xc1g5priz7`
In browser you can see that it returns:
`{"error":"No results found","error_code":20}`

**Comment by antonsoroko** [comment]
@burekas7 

for me `search_tmdb=577922` gives a lot of irrelevant results, like `The.First.Wave.2021`.
when `search_themoviedb=577922` gives me correct torrent for https://www.themoviedb.org/movie/577922-tenet

**Comment by burekas7** [comment]
It seems that you are right.
Basically this is hard to debug because now I'm getting results from RARBG with the original search url
```
[script.elementum.burst] [rarbg] Before keywords - Query: '{tmdb_id}' - Extra: 'search_themoviedb'
[script.elementum.burst] [rarbg] Skip fallback as there are already results
```

Because previously I got zero so in the log I check the rarbg search urls and I see that.

But if we back to the tmdb fallback:
So why I don't get results in the browser with "search_themoviedb=577922", or I should get only by using it with the addon?

**Comment by antonsoroko** [comment]
i opened your link in browser and i got results. but they have rate limiting - if you refresh page (or make several requests via elementum) - you will get `{"error":"No results found","error_code":20}`.
so you just need to open your link after "some" time.

**Comment by burekas7** [comment]
@antonsoroko 
Oh you're right, this explains everything.
Now I got results.

I will close the PR.

**Pull request closed without merging**
