### PR TITLE
Tweaks to providers.json

### PR DESCRIPTION
**Pull request by guglicap**
The main fix is to replace all the `title:original` lines with just `title` or the specific language (eg. `title:it`, `title:fr`, `title:hu`, etc).
Other minor things include fixes already in #104 and #105, fixes for `ilcorsaronero` and fixes for some misused "EXTRA" lines.

### CODE REVIEW

**Comment by elgatito** [comment]
> The main fix is to replace all the `title:original` lines with just `title` or the specific language (eg. `title:it`, `title:fr`, `title:hu`, etc).

This is not good. When you set some specific language in the query - you expect to find that translation of a title on the website, and on many trackers it will fail in a lot of cases, because translations are wrong too often.

**Comment by guglicap** [comment]
I don't think using `title:original` almost everywhere is good either, since a lot of "English" trackers actually also have many non-English torrents. For example, I'm in Italy and I get most of my torrents now from 1137x (which I modified to use `title`). I think using `title` everywhere is reasonable, as that reflects kodi language and using `title:lang` on actual lang only providers doesn't make much of difference, really.

**Comment by elgatito** [comment]
> I think using `title` everywhere is reasonable, as that reflects kodi language and using `title:lang` on actual lang only providers doesn't make much of difference, really.

No it does not. It can be true for some trackers. Especially if TMDB translations match the title, used on the tracker. But more often title contains both original (or english) and local translation.

**Comment by elgatito** [comment]
I understand *why* you want these changes and what they do, but you can't just apply it everywhere. 
Instead, push a PR for changing trackers that you are sure about and which you tested personally.

**Comment by guglicap** [comment]
Are you okay with `title` instead of `title:original` though? Also, if you have something to say on the other changes, let me know. I know it's not beautiful to have this big pull request but I wasn't sure many little ones would have been better instead. Should I close this one and open individual ones for the other commits?

**Comment by elgatito** [comment]
> Are you okay with `title` instead of `title:original` though?

Yes,  with providers, that you've checked work fine after change.

> Also, if you have something to say on the other changes, let me know. 

If you talk about few queries changes - then looks fine.

> Should I close this one and open individual ones for the other commits?

Up to you. It's always better to have clean commit, instead of commiting and fixing in the next one.

**Comment by guglicap** [comment]
Alright, I'll close this and #104 and re submit them in a cleaner way.

**Pull request closed without merging**
