### PR TITLE
Update EZTVX.to + Fix code

### PR DESCRIPTION
**Pull request by SubEdict**
**Update 2**: EZTV.LI now redirects to eztvx.to but none of them fetch results.
Help is needed.

### CODE REVIEW

**Comment by antonsoroko** [comment]
@SubEdict 
this is because they hide links now by default.

do this change:
```
        "base_url": "https://eztvx.to/search/QUERYEXTRA",
        "post_data": "{'layout': 'def_wlinks'}",
```
and it will work (at least it works for me).
Then update PR please.

**Comment by antonsoroko** [comment]
@SubEdict 
To be clear - I do not know "when" or even "if" author will accept this change and create new release.
If you want - you can try to contact him directly.

**Comment by elgatito** [comment]
@SubEdict  @antonsoroko this one is ready to be merged?

**Comment by SubEdict** [comment]
@elgatito Yes, those two line works great.
Thanks

**Pull request merged**
