### PR TITLE
remove {en:original} from RARBG queries

### PR DESCRIPTION
**Pull request by ShlomiD83**
I discovered that querying RARBG with "{title:en:original} {year}" doesn't return results in some cases.
removing en & original mitigates the issue and RARBG returns results just fine.
for example "A Quiet Place Part II", you can try for yourself.

thanks.

### CODE REVIEW

**Comment by antonsoroko** [comment]
@ShlomiD83 
this seems to be unlikely.
`original` means to use untranslated title, but for this movies it is the same as `en`.
and en means to use translated to `en` title, which again the same.

also since this tracker has `"languages": "en",` - we do not remove accents for `en`. and we never remove accents for `original`.

---

the issue with this movie is that tmdb has year as 2021 and rarbg has it as 2020 (from imdb, i guess) - so it gives no results for main query.

also in this case you fall into 
```
        "movie_extra_fallback": "search_imdb",
        "movie_keywords_fallback": "{imdb_id}",
```
that uses imdb number so it finds this movie.

also note that sometimes rarbg simply does not return results - that's why sometimes all queries (including fallback) fail - so you do not have results.

**Comment by ShlomiD83** [comment]
Before removing en and original it searched in french and returned 0 results.

**Comment by ShlomiD83** [comment]
my bad, please disregard.

**Comment by antonsoroko** [comment]
>Before removing en and original it searched in french and returned 0 results.

this is strange. with rarbg burst should not use any other languages except `en` and `original` (for this movie - also `en`).

**Comment by ShlomiD83** [comment]
> > Before removing en and original it searched in french and returned 0 results.
> 
> this is strange. with rarbg burst should not use any other languages except `en` and `original` (for this movie - also `en`).

I think I was mistaken, please disregard.

**Comment by antonsoroko** [comment]
ok.
anyway, just remember that sometimes rarbg simply does not return results - so you have to search again after small timeout.
happens often to me.

**Comment by ShlomiD83** [comment]
> ok.
> anyway, just remember that sometimes rarbg simply does not return results - so you have to search again after small timeout.
> happens often to me.

Yeah, I know. It's a limitation of the API.

**Pull request closed without merging**
