### PR TITLE
Add BitSearch tracker

### LINKED ISSUE #329: bitsearch.to provider
please add this site https://bitsearch.to/

### PR DESCRIPTION
**Pull request by antonsoroko**
Fixes #329

### CODE REVIEW

**Review by naveen1hot — APPROVED** [review]

**Review by naveen1hot — COMMENTED** [review]
Hello @antonsoroko i am getting the results but failed at resolving links(not playing). sorry to trouble you. just i want to share the status of your commit. thanks..

**Comment by antonsoroko** [comment]
@naveen1hot as I mentioned in #329 I need more info from you:

1. I would need a full log file with debug enabled in elementum and kodi from you.
See http://elementum.surge.sh/contribute/log/ for a guide.

2. On a side note, for torrent files BitSearch uses `iTorrents.org is a free service for caching torrent files online.` and as I can see that sometimes it give us timeout when we try to download torrent file, so you need to try again. This is because of cloudflare protection against bots (burst is a bot). Nothing we can do here.
Does this issue happen all the time for you? I guess you need to try several times.

3. Try with this change (it uses magnet links instead of torrent files):
`"torrent": "item(tag='a', select=('class', 'dl-magnet'), attribute='href', order=1)"`
And tell me which approach works better. Create another log file if you will have issues.

(Note that because of cloudflare protection, sometimes BitSearch website itself does not accept connections - thus no results, so you have to run search again).

**Comment by naveen1hot** [comment]
Hello!!! @antonsoroko .. its working very well now. thanks so much for your help and efforts.

**Comment by antonsoroko** [comment]
@elgatito Hi. Can you please merge PRs? Thank you!

**Pull request merged**
