### PR TITLE
Last element as point of reference

### PR DESCRIPTION
**Pull request by mancuniancol**
I've added support to use the last item as reference.
Ex:
item(tag='td', order=1)
it takes the first element

item(tag='td', order=0)
it takes the last element

item(tag='td', order=-n)
it takes the last element -n

Some sites don't have constant elements due to a extra information.  Then, it is easier to keep track using the last element as point of reference.

### CODE REVIEW

**Comment by elgatito** [comment]
Have you tested the changes in list_() -> list() ? 
I'm not familiar with that code.

**Comment by mancuniancol** [comment]
Well, the change was to avoid shadow of the native list function.  I use pycharm, I used to have an alert for that, but not anymore.

Any case, I think that the reverting doesn't affect the function.  But, I think that it is clearly as it was before.

I will revert that part and I will do some tests.

**Comment by elgatito** [comment]
@mancuniancol  I have pushed the change into 0.0.17, you can checkout and test.

**Comment by mancuniancol** [comment]
Perfect.  I will.  I keep you posted.

**Comment by mancuniancol** [comment]
I've been doing some test in my machine and it is working correctly reverting the list method to list_. I will upload that change this weekend

**Pull request merged**
