### PR TITLE
Fix megapeer as of 27.06.2024

### PR DESCRIPTION
**Pull request by antonsoroko**
New parser.

### CODE REVIEW

**Comment by antonsoroko** [comment]
@elgatito can we merge it please?

**Comment by elgatito** [comment]
@antonsoroko Anything else would land into Burst? Or release can be done?

**Comment by antonsoroko** [comment]
@elgatito I do have few changes that I recently made, but I still need to push and describe them. 
Next Monday/Tuesday I will create PRs. 
Thanks.

**Comment by antonsoroko** [comment]
@elgatito i pushed all the changes i had.
i also can remove legacy code mentioned in https://github.com/elgatito/script.elementum.burst/issues/417#issuecomment-2389004911
but if you decide to keep legacy code - then release can be done.
thank you.

**Pull request merged**
